on:
  push:
    paths:
      - '**/collection.xml'
      - '**/resource.xml'
      - '.github/workflows/build.yml'
  workflow_dispatch:
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [{
              "id": "softalks",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}" 
            }, {
              "id": "archetype",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
          repositories: |
            [{
              "id": "archetype",
              "url": "https://maven.pkg.github.com/agencia-tributaria/entidad",
              "releases": {
                "enabled": false
              }, 
              "snapshots": {
                "enabled": true
              }
            }]
          plugin_repositories: |
            [{
              "id": "softalks",
              "url": "https://maven.pkg.github.com/softalks/maven-archetype",
              "releases": {
                "enabled": false
              }, 
              "snapshots": {
                "enabled": true
              }
            }, {
              "id": "apache.snapshots",
              "url": "https://repository.apache.org/snapshots/",
              "releases": {
                "enabled": false
                }, 
                "snapshots": {
                  "enabled": true
                }
            }]
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: main
        run: |
          if test -z "${{ steps.files.outputs.removed }}"; then echo "No files removed (OK)"; else exit 1001; fi
          if test -z "${{ steps.files.outputs.renamed }}"; then echo "No files renamed (OK)"; else exit 1002; fi
          build () {
            echo "action: " $1
            for changed in $2; do
              parent="$(dirname -- "$(readlink -f -- "$changed")")"
              cd $parent
              wget http://agencia-tributaria.github.io/resource_type/org.apache.maven-archetype-plugin.input.xml 
              if [ ! -d .mvn ]; then
                mkdir .mvn
                echo "-DarchetypeCatalog=local -DarchetypeGroupId=agencia-tributaria -DarchetypeArtifactId=entidad -DarchetypeVersion=1.0-SNAPSHOT" > .mvn/jvm.config
                echo "--batch-mode --update-snapshots" > .mvn/maven.config
              fi
              $REPO=${{ env.GITHUB_REPOSITORY }}
              $REPO=$(echo $REPO | cut -d'/' -f 2)
              $OWNER = ${{ env.GITHUB_REPOSITORY_OWNER }}
              mvn archetype:generate -DgroupId=$OWNER -DartifactId=$REPO.$changed -Dversion=1.0 -DartifactId=$REPO.$changed -Dpackage=es.aeat.$REPO.$changed -DgroupId=agencia-tributaria -DgroupIdPat=${{ secrets.GITHUB_TOKEN }}
              mvn org.apache.maven.plugins:maven-archetype-plugin:3.2.2-SNAPSHOT:generate -Dclass=Hello -DartifactId=adts.$changed -Dpackage=es.aeat.adts.$changed -DgroupId=agencia-tributaria -DgroupIdPat=${{ secrets.GITHUB_TOKEN }}
            done
          }
          if test -z "${{ steps.files.outputs.added    }}"; then echo "No files added"   ; else build "added"    ${{ steps.files.outputs.added    }}; fi
          if test -z "${{ steps.files.outputs.modified }}"; then echo "No files modified"; else build "modified" ${{ steps.files.outputs.modified }}; fi
          cd adts-hello/src/main/java/es/aeat/adts
          pwd
          cat --number test.xml
