on:
  push:
    paths:
      - '**/collection.xml'
      - '**/resource.xml'
      - '.github/workflows/build.yml'
  workflow_dispatch:
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "softalks",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}" 
            }, {
              "id": "archetype",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: main
        run: |
          if test -z "${{ steps.files.outputs.removed }}"; then echo "No files removed (OK)"; else exit 1001; fi
          if test -z "${{ steps.files.outputs.renamed }}"; then echo "No files renamed (OK)"; else exit 1002; fi
          build () {
            echo "change: " $1
            for changed in $2; do
              parent_dir="$(dirname -- "$(readlink -f -- "$changed")")"
              cd $parent_dir
              wget http://agencia-tributaria.github.io/resource_type/org.apache.maven-archetype-plugin.input.xml 
              echo "-DarchetypeCatalog=local -DarchetypeGroupId=agencia-tributaria -DarchetypeArtifactId=entidad -DarchetypeVersion=1.0-SNAPSHOT" > .mvn/jvm.config
              echo "--batch-mode --update-snapshots" > .mvn/maven.config
              mvn org.apache.maven.plugins:maven-archetype-plugin:3.2.2-SNAPSHOT:generate -Dclass=Hello -DartifactId=adts-hello -Dpackage=es.aeat.adts -DgroupId=agencia-tributaria -DgroupIdPat=${{ secrets.GITHUB_TOKEN }}
            done
          }
          if test -z "${{ steps.files.outputs.added    }}"; then echo "No files added"   ; else build "added"    ${{ steps.files.outputs.added    }}; fi
          if test -z "${{ steps.files.outputs.modified }}"; then echo "No files modified"; else build "modified" ${{ steps.files.outputs.modified }}; fi
          cd adts-hello/src/main/java/es/aeat/adts
          pwd
          cat --number test.xml
